controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_front:
    path: /
    controller: App\Controller\FrontController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::login
