controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_front:
    path: /front
    controller: App\Controller\FrontController::index

app_home:
    path: /
    controller: App\Controller\HomeController::index

