parameters:
    logement_directory: '%kernel.project_dir%/public/uploads/logement'

services:
    App\Twig\Extension\TimeAgoExtension: ~

    App\Service\ProfanityFilterService:
        arguments:
            $client: '@http_client'  # Symfony HTTP Client
            $requestFactory: '@nyholm.psr7.factory'  # Custom service alias for Nyholm PSR-7 Factory
            $uriFactory: '@nyholm.psr7.factory'  # Same factory for UriFactoryInterface

    # Default service configuration
    _defaults:
        autowire: true      # Automatically inject dependencies.
        autoconfigure: true # Automatically register services as commands, event subscribers, etc.

    # Makes classes in src/ available as services
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        autowire: true
        autoconfigure: true

    # Manually define the PSR-17 factory service for Nyholm
    nyholm.psr7.factory:
        class: Nyholm\Psr7\Factory\Psr17Factory

    # PSR-7 message factories (use the custom Nyholm factory)
    Psr\Http\Message\RequestFactoryInterface: '@nyholm.psr7.factory'
    Psr\Http\Message\StreamFactoryInterface: '@nyholm.psr7.factory'
    Psr\Http\Message\UriFactoryInterface: '@nyholm.psr7.factory'
